name: Terraform Auto Format

on:
  push:
    branches-ignore:
      - main

jobs:
  terraform-fmt:
    name: Auto-format Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform fmt
        run: terraform fmt -recursive

      - name: Commit and push changes
        run: |
          git config user.name "terraform-bot"
          git config user.email "terraform-bot@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore(terraform): auto format"
            git push
          else
            echo "Nothing to commit"
          fi
