name: Terraform Check and Format

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Terraform Lint and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Find all Terraform directories
        id: find_dirs
        run: |
          MODULE_DIRS=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u)
          echo "$MODULE_DIRS" > module_dirs.txt
          echo "directories<<EOF" >> $GITHUB_OUTPUT
          echo "$MODULE_DIRS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run terraform fmt check
        run: |
          FAIL=0
          for dir in $(cat module_dirs.txt); do
            echo "→ Checking format in $dir"
            terraform fmt -check -recursive "$dir" || FAIL=1
          done
          exit $FAIL

      - name: Run terraform validate
        run: |
          for dir in $(cat module_dirs.txt); do
            echo "→ Validating $dir"
            terraform -chdir="$dir" init -backend=false
            terraform -chdir="$dir" validate
          done

      - name: Leave PR comment if formatting failed
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ⚠️ Terraform formatting check **failed**.

            Please run `terraform fmt -recursive` locally and commit the changes.
